"""empty message

Revision ID: a1539dad9062
Revises: 9dc3780f3d09
Create Date: 2023-01-26 16:25:03.358437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1539dad9062'
down_revision = '9dc3780f3d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone-medication',
    sa.Column('drone_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drone.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drone-medication')
    # ### end Alembic commands ###
